services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoPersonio\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,Entity,Message,ContaoPersonioBundle.php}

    InspiredMinds\ContaoPersonio\PersonioRecruitingApi:
        arguments:
            $personioRecruitingApiClient: '@contao_personio.personio_recruiting_api_client'
            $personioRecruitingApiRateLimiterFactory: '@contao_personio.rate_limit.personio_recruiting_api_factory'

    InspiredMinds\ContaoPersonio\Controller\ContentElement\PersonioJobApplicationController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    InspiredMinds\ContaoPersonio\HttpClient\PersonioAuthenticatedApiClientFactory:
        arguments:
            $personioAuthApiRateLimiterFactory: '@contao_personio.rate_limit.personio_auth_api_factory'

    contao_personio.personio_authenticated_api_client:
        class: Symfony\Contracts\HttpClient\HttpClientInteface
        factory: '@InspiredMinds\ContaoPersonio\HttpClient\PersonioAuthenticatedApiClientFactory'

    contao_personio.rate_limit.personio_api_storage:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            - '@cache.rate_limiter'

    contao_personio.rate_limit.personio_auth_api_factory:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            - { id: contao_personio.personio_api, policy: fixed_window, limit: 60, interval: 1 minute }
            - '@contao_personio.rate_limit.personio_api_storage'
            - '@?lock_factory'

    contao_personio.rate_limit.personio_recruiting_api_factory:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            - { id: contao_personio.personio_api, policy: fixed_window, limit: 20, interval: 1 minute }
            - '@contao_personio.rate_limit.personio_api_storage'
            - '@?lock_factory'
